"""Reproduce the superseded first-pass reference briefs, prompts and gallery.

Use style_revision.py build for the current selection and app-language review.

This script writes text only. Generated raster images are never transformed.
"""

import html
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
BRIEFS = {
    "chemex": ("Glass hourglass body: broad open conical top, narrow waist with a wooden collar and leather tie, rounded lower carafe, and a visible pour-spout channel. Use the Classic's handle-free silhouette.", "No loop handle, separate cone, mechanical valve, plunger, paper packaging, or added mug."),
    "automatic-drip": ("Complete automatic filter machine: tall left heater column and clear water reservoir above it, short shower arm extending to the right filter basket, glass carafe directly below that basket, and a shared low rectangular base. Simplify hardware while retaining this unmistakable arrangement.", "No portafilter, steam wand, bean hopper, espresso group head, separate kettle, or extra cups."),
    "pulsar": ("Straight clear cylindrical brewing chamber, broad flat black shower cap on top, sturdy black footed base, and the small external flow-control lever at the side of the base. Clearly retain the shower cap, chamber and valve as distinct parts.", "No cone, loop handle, piston, plunger rod, carafe, or curved glass hourglass."),
    "v60": ("Open circular cone narrowing toward a single bottom outlet, characteristic spiral ribs, small loop handle on the right, and a flat circular support flange. Match the photographed V60 02 geometry; omit its box.", "No wedge-shaped flat seam, chunky valve base, Switch lever, plunger, packaging or brand marks."),
    "clever": ("Broad tapered wedge-shaped brewing chamber with a wide opening, large curved right-side handle, broad circular release base and short feet. Isolate the Clever from the brewing photograph. Show an open rim with a simple ivory paper filter, and preserve its chamber-to-release-base proportion.", "No pouring kettle, water stream, table, serving carafe, logos, spiral V60 cone, or external Switch lever. Do not invent a lid or screw insert."),
    "hario-switch": ("Ribbed glass V60 cone seated in a substantial dark flared silicone valve base, with its external transparent switch lever visibly projecting from the side. The photographed glass cone has no loop handle. Retain the heavier valve base and lever so this cannot read as a plain V60.", "No V60 loop handle, wooden collar, plunger, flat shower lid, mug, or packaging."),
    "kalita-wave": ("Broad shallow truncated stainless-steel cone with a flat lower floor, horizontal stepped bands, a low round support flange and small right-side loop handle. Keep the wide shallow bowl shape, rather than a pointed V60 cone.", "No spiral ribs, conical pointed bottom, valve lever, plunger, lid, or mug."),
    "melitta": ("Wide oval opening tapering into a wedge body with a short flat bottom seam, straight vertical interior ribs, right-side loop handle, and broad round support flange. Follow the unboxed 1x4 photograph, including the low front viewing opening at the flange. Keep the wedge visibly different from the circular spiral V60.", "No spiral ribs, circular pointed cone, mechanical valve, packaging, printed brand, or numbers."),
    "turkish": ("One small copper cezve with a rounded wider lower body, narrower neck, open flared mouth and a very long slim handle rising diagonally to the right. Preserve the full handle and its attachment from the photo; simplify hammered detail into a few soft copper highlights.", "No lid, side loop handle, moka chambers, flame, stove, coffee cup, or steam."),
    "phin": ("One assembled Vietnamese gravity phin: short wide cylindrical metal chamber, small side loop handle, shallow fitted cap, and a broad flat perforated support plate below. The exploded photograph supplies the component shapes; assemble the pieces in their real order. The gravity insert rests inside and is hidden beneath the fitted lid.", "No exploded arrangement, arrows, labels, threaded screw or long piston rod, espresso handle, cup, or extra loose pieces."),
    "french-press": ("Cylindrical glass jug in a simple metal frame, curved black side handle, short pour spout, domed lid, round plunger knob and central straight rod leading to a visible mesh disc inside the jug. Use the Chambord photograph's silhouette and support feet.", "No V60 cone, separate filter basket, extra mug, kettle, printed markings, or steam."),
    "aeropress": ("One assembled upright AeroPress Original: dark translucent straight brewing chamber, piston emerging at the top with a broad flat top flange, broad lower support flange and standard filter cap at the bottom. Show a modest extension of the piston so the two overlapping cylinders are clear. Isolate only the brewer from the product photograph.", "No mug, scoop, stirrer, printed numbers, logos, side handle, long French-press rod, flow-control valve, or inverted position."),
    "espresso": ("One compact Bambino Plus-style espresso machine: tall rounded rectangular body, clean small circular front controls, portafilter locked under the brew group with its black handle clearly projecting forward, right-side steam wand, and drip tray beneath an open brewing area. Preserve the photographed group-to-tray and wand arrangement.", "No integrated grinder, bean hopper, pressure gauge, extra cups, printed control labels, or automatic-drip basket and carafe."),
    "moka-pot": ("Complete closed Moka Express: octagonal lower water chamber, screw-joint waist, octagonal upper collecting chamber with a left pour spout, hinged sloping lid and black knob, large black curved handle on the right, and a small safety valve on the lower chamber. Retain the distinctive two-chamber octagonal silhouette.", "No flames, stove, coffee cup, glass hourglass, percolator cylinder, steam, pressure gauge, or logo."),
    "cold-brew": ("One generic covered wide-mouth glass steeping jar with a simple screw lid, rounded shoulders, broad cylindrical body, and dark coffee-colored contents well below the lid. Use the single jar at the right of the photo for jar anatomy. Omit all embossing; show a little dark ground-coffee sediment at the bottom to suggest immersion brewing.", "No retail carton, cluster of jars, embossed lettering, measuring marks, integral filter basket, ice, straw, serving tumbler, spigot, or capacity claim."),
    "siphon": ("A complete Hario Technica-style siphon: upper straight glass brewing cylinder, descending central glass tube into the round lower globe, gasket at the joined neck, metal stand with a right-side handle supporting the globe, stable base and unlit alcohol lamp centered underneath the globe. Preserve the real joined two-chamber arrangement and stable support.", "No floating disconnected chambers, invented plumbing, pressure gauge, steampunk gear, flame, boiling liquid, coffee cup, or lettering."),
    "percolator": ("One electric percolator with a tall gently tapered cylindrical metal pot, fitted lid and black knob, long raised pouring spout on the left, black curved handle on the right, and a low black electric base. Match the photographed Presto silhouette; simplify tiny details.", "No cord, serving cup, saucer, branding, moka octagons, glass French-press chamber or plunger, tea infuser, or steam."),
}

STYLE = """Create a new square brewing-method icon using the two attached images.
Image 1 is equipment geometry reference only. Preserve that brewer's recognizable construction and proportions; remove the photo's background, packaging, text and unrelated objects.
Image 2 is the existing StarlitCoffee icon style reference only. Match its premium tactile enamel/clay treatment, deep ink-navy edges, periwinkle-blue planes, warm ivory highlights and restrained coffee-brown/copper accents. Do not copy its V60 geometry into this method.
One isolated complete brewer, front three-quarter view, slight view into open tops where relevant, soft upper-left light, rounded deliberate forms and strong readable silhouette at 48 pixels. Stylize surface materials into the shared palette without losing the distinctive hardware. Center the entire object with roughly 8 percent clear margin on every side; full handles, spouts, feet and lids inside the canvas. Genuine transparent background, alpha outside the object, no cast shadow platform, badge, border, scene, letters, numbers, logo, watermark or checkerboard. No hands or brewing action. This is an equipment recognition icon, not an operating instruction.
"""


def main():
    path = ROOT / "manifest.json"
    data = json.loads(path.read_text(encoding="utf-8-sig"))
    (ROOT / "prompts").mkdir(exist_ok=True)
    for item in data["methods"]:
        brief, avoid = BRIEFS[item["id"]]
        item.update({"geometry_brief": brief, "exclude": avoid, "reference_review": "Visually inspected; selected for equipment anatomy", "prompt_file": f"prompts/{item['id']}.txt", "input_roles": ["equipment geometry", "existing icon style"], "candidate_file": item.get("candidate_file", f"candidates/{item['id']}.png"), "review_status": item.get("review_status", "Awaiting generation and visual review")})
        prompt = STYLE + f"\nMethod: {item['name']}. Representative model: {item['model']}.\nEquipment anatomy: {brief}\nExclude: {avoid}\nDeliver exactly one transparent square icon."
        (ROOT / item["prompt_file"]).write_text(prompt + "\n", encoding="utf-8", newline="\n")
    data["photo_use"] = "Reference inputs for review only. Photographs remain attributed to their publishers; do not use as shipped artwork."
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8", newline="\n")
    e = html.escape
    cards = []
    for item in data["methods"]:
        candidate = ROOT / item["candidate_file"]
        preview = f'<img class="large" src="{e(item["candidate_file"])}" alt="Generated {e(item["name"])} equipment icon">' if candidate.exists() else '<div class="pending">Awaiting candidate</div>'
        mini = f'<img src="{e(item["candidate_file"])}" alt="">' if candidate.exists() else ''
        status = '' if item["review_status"] == "Reviewed design candidate" else f'<p class="status">{e(item["review_status"])}</p>'
        cards.append(f'''<article id="{e(item['id'])}"><h2>{e(item['name'])}</h2><p class="model">{e(item['model'])}</p><div class="stage">{preview}</div><div class="samples"><span class="light">{mini}</span><span class="dark">{mini}</span><span>48 px</span></div>{status}<details><summary>Photo &amp; icon brief</summary><img class="reference" src="{e(item['reference_file'])}" alt="Source equipment photograph for {e(item['name'])}"><p>{e(item['geometry_brief'])}</p><p><a href="{e(item['source_url'])}">Equipment source</a> · <a href="{e(item['prompt_file'])}">Exact generator prompt</a></p></details></article>''')
    document = '''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>StarlitCoffee · Brewing method icon review</title><style>
    *{box-sizing:border-box}body{margin:0;background:#f4f2ec;color:#182637;font:16px/1.5 system-ui,sans-serif}header,main{max-width:1240px;margin:auto;padding:28px}header{padding-bottom:0}h1{font-size:32px;line-height:1.15;margin:8px 0}header p{max-width:760px}.eyebrow,.model,.status{color:#51616e;font-size:13px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:18px}article{background:#fff;border:1px solid #dedfdc;border-radius:20px;padding:18px;min-width:0}h2{font-size:20px;margin:0}.model{margin:4px 0;min-height:40px}.stage{display:grid;place-items:center;height:180px;background:#eef0ef;border-radius:14px}.large{width:164px;height:164px;object-fit:contain}.samples{display:flex;align-items:center;gap:10px;margin-top:12px;color:#51616e;font-size:12px}.samples span{display:grid;place-items:center;border-radius:10px}.samples .light,.samples .dark{width:64px;height:64px}.light{background:#f8f5ee}.dark{background:#192b40}.samples img{width:48px;height:48px;object-fit:contain}details{margin-top:12px;border-top:1px solid #e4e4e0;padding-top:8px}summary{min-height:48px;cursor:pointer;display:flex;align-items:center;font-weight:600}summary:focus-visible,a:focus-visible{outline:3px solid #6655c7;outline-offset:4px}.reference{width:100%;max-height:260px;object-fit:contain;margin-top:8px;background:white}a{color:#3d4c91;overflow-wrap:anywhere}details p{font-size:14px}footer{padding:24px 0;color:#51616e;font-size:14px}button{font:inherit;padding:12px 18px;border-radius:12px;border:1px solid #bec5cc;background:#fff;min-height:48px;cursor:pointer}.pending{color:#51616e}body.dark-page{background:#142234;color:#ecf0f3}body.dark-page article{background:#22354d;border-color:#40516a}body.dark-page .stage{background:#1a2b40}body.dark-page .model,body.dark-page .status,body.dark-page .eyebrow,body.dark-page footer{color:#b6c4d4}body.dark-page a{color:#c3caff}@media(max-width:400px){header,main{padding:18px}.grid{grid-template-columns:minmax(0,1fr)}h1{font-size:28px}}
    body.dark-page .samples{color:#b6c4d4}body.dark-page details{border-color:#40516a}
    </style><header><p class="eyebrow">STARLITCOFFEE · DESIGN REVIEW · 2 OCT 2026</p><h1>Recognizable brewers. One visual family.</h1><p>17 equipment references, individual icon briefs, and transparent generated candidates. Open any card to compare its hardware with the source photo.</p><button onclick="document.body.classList.toggle('dark-page');this.setAttribute('aria-pressed',document.body.classList.contains('dark-page'))" aria-pressed="false">Dark background</button> <a href="README.md">Review notes</a></header><main><div class="grid">''' + "\n".join(cards) + '''</div><footer>Design candidates for recognition only. Android assets have not been replaced. These icons do not demonstrate brewing procedure or establish batch capacity. <a href="manifest.json">Provenance manifest</a></footer></main></html>'''
    (ROOT / "index.html").write_text(document, encoding="utf-8", newline="\n")
    tiles = []
    for item in data["methods"]:
        if (ROOT / item["candidate_file"]).exists():
            tiles.append(f'<a class="tile" href="index.html#{e(item["id"])}"><img src="{e(item["candidate_file"])}" alt=""><span>{e(item["name"])}</span></a>')
    sheet = '''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>StarlitCoffee · 17 brewing methods</title><style>*{box-sizing:border-box}body{margin:0;padding:28px;background:#f4f2ec;color:#182637;font:16px/1.4 system-ui,sans-serif}header,main,footer{max-width:1200px;margin:auto}h1{font-size:30px;margin:4px 0}p{color:#51616e;margin:4px 0 20px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:14px}.tile{display:flex;flex-direction:column;align-items:center;justify-content:center;gap:10px;min-height:178px;padding:14px;border-radius:18px;background:white;color:inherit;text-decoration:none;border:1px solid #dedfdc;text-align:center}.tile img{width:122px;height:122px;object-fit:contain}.tile span{font-size:14px;font-weight:600}.tile:focus-visible{outline:3px solid #6655c7;outline-offset:3px}footer{font-size:13px;color:#51616e;padding-top:18px}a{color:#3d4c91}@media(max-width:400px){body{padding:18px}h1{font-size:26px}}</style><header><h1>17 methods. One visual family.</h1><p>Equipment photographs + individual briefs + a shared icon style.</p></header><main class="grid">''' + "\n".join(tiles) + '''</main><footer>StarlitCoffee · Design candidates · 2 October 2026 · <a href="index.html">Photos, prompts &amp; 48 px review</a></footer></html>'''
    (ROOT / "sheet.html").write_text(sheet, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
